title: Dmitry ANISIMOV
description: Senior 3D Geometry · C++ Engineer · PhD
baseurl: ""
url: https://anisimov.work

theme: cvless

# site settings
taglong: Senior 3D Geometry · C++ Engineer · PhD
tagshort: Senior 3D Geometry · C++ Engineer · PhD

# author settings
author:
  name: Dmitry ANISIMOV
  email: rudanston@gmail.com
photo: assets/files/photo.jpg
joblines:
  - Samp
  - Geometry Lead
  - Paris, France
address: Paris, France
phone: +33767372252

# profile links
profile:
  instagram: https://www.instagram.com/rudanston
  linkedin: https://www.linkedin.com/in/dmitry-anisimov
  github: https://github.com/danston
  cv: assets/files/en-cv-anisimov.pdf

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  